// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_edgelist_cpp
arma::umat get_edgelist_cpp(const arma::mat& adj, const arma::vec& C, const int E, const int n);
RcppExport SEXP _MCGoFSBM_get_edgelist_cpp(SEXP adjSEXP, SEXP CSEXP, SEXP ESEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const int >::type E(ESEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(get_edgelist_cpp(adj, C, E, n));
    return rcpp_result_gen;
END_RCPP
}
// get_edgelist_comp_cpp
arma::umat get_edgelist_comp_cpp(const arma::mat& adj, const arma::vec& C, const int E, const int n);
RcppExport SEXP _MCGoFSBM_get_edgelist_comp_cpp(SEXP adjSEXP, SEXP CSEXP, SEXP ESEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const int >::type E(ESEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(get_edgelist_comp_cpp(adj, C, E, n));
    return rcpp_result_gen;
END_RCPP
}
// get_mle_cpp
arma::mat get_mle_cpp(const arma::mat& A, const arma::vec& C, const int k);
RcppExport SEXP _MCGoFSBM_get_mle_cpp(SEXP ASEXP, SEXP CSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mle_cpp(A, C, k));
    return rcpp_result_gen;
END_RCPP
}
// graphchi_cpp
double graphchi_cpp(const arma::mat& A, const arma::mat& p_mle, const arma::vec& C, const int n, const int k);
RcppExport SEXP _MCGoFSBM_graphchi_cpp(SEXP ASEXP, SEXP p_mleSEXP, SEXP CSEXP, SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type p_mle(p_mleSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(graphchi_cpp(A, p_mle, C, n, k));
    return rcpp_result_gen;
END_RCPP
}
// sample_a_move_cpp
arma::mat sample_a_move_cpp(const arma::mat& adj, const arma::vec& C, const int n, const int k);
RcppExport SEXP _MCGoFSBM_sample_a_move_cpp(SEXP adjSEXP, SEXP CSEXP, SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type adj(adjSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_a_move_cpp(adj, C, n, k));
    return rcpp_result_gen;
END_RCPP
}
// graph_chain_on_fiber
arma::vec graph_chain_on_fiber(const arma::mat& A, const arma::vec& C, const int n, const int k, const int numGraphs);
RcppExport SEXP _MCGoFSBM_graph_chain_on_fiber(SEXP ASEXP, SEXP CSEXP, SEXP nSEXP, SEXP kSEXP, SEXP numGraphsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const int >::type numGraphs(numGraphsSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_chain_on_fiber(A, C, n, k, numGraphs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MCGoFSBM_get_edgelist_cpp", (DL_FUNC) &_MCGoFSBM_get_edgelist_cpp, 4},
    {"_MCGoFSBM_get_edgelist_comp_cpp", (DL_FUNC) &_MCGoFSBM_get_edgelist_comp_cpp, 4},
    {"_MCGoFSBM_get_mle_cpp", (DL_FUNC) &_MCGoFSBM_get_mle_cpp, 3},
    {"_MCGoFSBM_graphchi_cpp", (DL_FUNC) &_MCGoFSBM_graphchi_cpp, 5},
    {"_MCGoFSBM_sample_a_move_cpp", (DL_FUNC) &_MCGoFSBM_sample_a_move_cpp, 4},
    {"_MCGoFSBM_graph_chain_on_fiber", (DL_FUNC) &_MCGoFSBM_graph_chain_on_fiber, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_MCGoFSBM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
